### ISSUE TITLE
Error message in field

### ISSUE THREAD

**Issue by HitogiDev** [Ajatt-Tools/Furigana#5]
I don't know why but in some cards this message is in the field where the addon should generate the readings: "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.", the reding is in the sentence so it does the work but I need to delete that message in some cards.

OS name: Windows 10
OS version: 21H2 Build 19044.2364
Anki version: ⁨2.1.56

Screenshot:

![imagen](https://user-images.githubusercontent.com/31047609/211445045-de35cc0e-a609-488c-96f9-5a87223241cb.png)

**Comment by tatsumoto-ren** [comment]
"This application has requested the Runtime to terminate it in an unusual way." is the output from mecab. I would assume it happened because mecab took too long to respond or there was some garbage in the output.

**Comment by HitogiDev** [comment]
Ok, so I guess this issue doesn't belong here since is not a problem with this addon per se.
