### ISSUE TITLE
Optional configuration to only provide furigana for only 1 reading?

### ISSUE THREAD

**Issue by MF-Billings** [Ajatt-Tools/Furigana#6]
Is it possible to revert to the old behavior where furigana for only 1 reading is generated?  This used to be the behavior a few weeks ago but it's changed recently.  Now I end up having to make more adjustments now than before when it only provided 1.

Windows 10 Home
OS Build: 19044.2728
Anki version: ⁨2.1.56 (07fd88dd)⁩

Here's an image of what I mean.  The addon used to only generate 1 of the potential furigana but now it's generating multiple.  
![image](https://user-images.githubusercontent.com/9014431/225938930-406f8826-62f5-4b4f-be9a-093cb560c3e1.png)

Thanks for your help.  This addon is great btw, a huge time saver!

**Comment by tatsumoto-ren** [comment]
> Is it possible to revert to the old behavior where furigana for only 1 reading is generated? 

Open Anki, select "AJT" > "Japanese Options..." > "Furigana" > "Maximum results = 1".

This should do.

**Comment by MF-Billings** [comment]
Works like a charm.  Ty!
